"""Builds CONTEXT.md — the file agy reads to understand your current workspace."""
import json
from datetime import datetime
from pathlib import Path

from intel.project_scanner import load_registry
from intel.agy_parser import get_project_agy_history
from intel.gmail_poller import load_inbox

CONTEXT_FILE = Path(__file__).resolve().parents[1] / "agy_workspace" / "CONTEXT.md"

def build_context() -> str:
    now = datetime.now()
    reg = load_registry()
    projects = reg.get("projects", [])
    active = [p for p in projects if p.get("status") == "active"]
    inbox  = load_inbox(days=7)
    unread_inbox = [i for i in inbox if i.get("platform") == "upwork"]

    lines = [
        f"# MAYA Context — {now.strftime('%A, %B %d, %Y %H:%M')}",
        "",
        "> This file is auto-generated by MAYA dashboard. Read it at session start.",
        "> You are working as a personal AI assistant for this workspace.",
        "",
        "---",
        "",
        f"## Active Projects ({len(active)})",
        "",
    ]

    for p in sorted(active, key=lambda x: x.get("last_agy_date", ""), reverse=True)[:10]:
        lines.append(f"### {p['name']}")
        lines.append(f"- **Path:** `{p['path']}`")
        lines.append(f"- **Platform:** {p.get('platform', 'local')}")
        if p.get("client"):
            lines.append(f"- **Client:** {p['client']}")
        lines.append(f"- **Last agy session:** {p.get('last_agy_date', 'unknown')} ({p.get('agy_msg_count', 0)} total messages)")
        if p.get("notes"):
            lines.append(f"- **Notes:** {p['notes']}")
        if p.get("next_actions"):
            lines.append("- **Next actions:**")
            for a in p["next_actions"]:
                lines.append(f"  - [ ] {a}")
        # Recent agy prompts for this project
        recent = get_project_agy_history(p["path"], limit=3)
        if recent:
            lines.append("- **Recent work:**")
            for r in recent:
                lines.append(f"  - `{r['date']}` — {r['text'][:100]}")
        lines.append("")

    if unread_inbox:
        lines += [
            "---",
            "",
            f"## Upwork Inbox ({len(unread_inbox)} messages)",
            "",
        ]
        for item in unread_inbox[:10]:
            lines.append(f"- **{item['date']}** | {item['subject']}")
            lines.append(f"  From: {item['from']}")
            lines.append(f"  Action needed: **{item['action']}**")
            if item.get("snippet"):
                lines.append(f"  > {item['snippet'][:150]}")
            lines.append("")

    lines += [
        "---",
        "",
        "## Your Role as agy Assistant",
        "",
        "When working in any project folder, you already know the context above.",
        "You can:",
        "- Reference `next_actions` to suggest what to work on",
        "- Update `D:\\AntigravityDashboard\\projects\\registry.json` when work is done",
        "- Write new inbox items to `D:\\AntigravityDashboard\\inbox\\`",
        "- Regenerate this file by running: `python D:\\AntigravityDashboard\\intel\\context_builder.py`",
        "",
        "---",
        f"*Generated by MAYA · {now.isoformat()}*",
    ]

    return "\n".join(lines)

def write_context() -> Path:
    CONTEXT_FILE.parent.mkdir(parents=True, exist_ok=True)
    content = build_context()
    CONTEXT_FILE.write_text(content, encoding="utf-8")
    return CONTEXT_FILE

if __name__ == "__main__":
    p = write_context()
    print(f"Context written to {p}")
    print(CONTEXT_FILE.read_text(encoding="utf-8")[:500])
